### ISSUE TITLE
Warn in the console

### ISSUE THREAD

**Issue by AxDevv** [LoneDev6/RPGhuds#22]
[09:31:46 WARN]: [RPGhuds] Task #5068 for RPGhuds v1.2.0 generated an exception
java.lang.IndexOutOfBoundsException: Index 3 out of bounds for length 3
at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266) ~[?:?]
at java.util.Objects.checkIndex(Objects.java:359) ~[?:?]
at java.util.ArrayList.get(ArrayList.java:427) ~[?:?]
at java.util.Collections$SynchronizedList.get(Collections.java:2498) ~[?:?]
at ia.m.aL.t(SourceFile:53) ~[ItemsAdder_3.3.0b-r5.jar:?]
at ia.m.bf.x(SourceFile:106) ~[ItemsAdder_3.3.0b-r5.jar:?]
at ia.m.bf.r(SourceFile:92) ~[ItemsAdder_3.3.0b-r5.jar:?]
at ia.m.bf.aE(SourceFile:113) ~[ItemsAdder_3.3.0b-r5.jar:?]
at dev.lone.itemsadder.api.FontImages.PlayerHudsHolderWrapper.sendUpdate(SourceFile:42) ~[ItemsAdder_3.3.0b-r5.jar:?]
at dev.lone.rpghuds.core.data.PlayerData.sendPacket(PlayerData.java:61) ~[RPGhuds_1.2.0.jar:?]
at dev.lone.rpghuds.core.data.PlayerData.refreshHuds(PlayerData.java:54) ~[RPGhuds_1.2.0.jar:?]
at dev.lone.rpghuds.core.data.PlayerData.refreshAllHuds(PlayerData.java:36) ~[RPGhuds_1.2.0.jar:?]
at dev.lone.rpghuds.core.RPGHuds.lambda$scheduleRefresh$0(RPGHuds.java:228) ~[RPGhuds_1.2.0.jar:?]
at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.3.jar:git-Purpur-1894]
at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.3.jar:git-Purpur-1894]
at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.3.jar:git-Purpur-1894]
at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:482) ~[purpur-1.19.3.jar:git-Purpur-1894]
at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1894]
at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1894]
at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1894]
at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by LoneDev6** [comment]
Post the whole log.
